# -*- coding: utf-8 -*-
"""CSCI_470_Project_Class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hXw-QNTfLErq0eM4aIdAPNhi4c0dB2y7
"""

specialCharacters = {1: "\alpha " 
                    2: "\beta "
                    3: "\gamma "
                    4: "\delta "
                    5: "\epsilon "
                    6: "\zeta "
                    7: "\eta "
                    8: "\varepsilon "
                    9: "\theta "
                    10: "\iota "
                    11: "\kappa "
                    12: "\vartheta "
                    13: "\lambda "
                    14: "\mu "
                    15: "\nu "
                    16: "\xi "
                    17: "\pi "
                    18: "\ro "
                    19: "\sigma "
                    20: "\tau "
                    21: "\upsilon "
                    22: "\phi "
                    23: "\chi "
                    24: "\psi "
                    25: "\omega "
                    26: "\Gamma "
                    27: "\Delta "
                    28: "\Theta "
                    29: "\Lambda "
                    30: "\Xi "
                    31: "\Pi "
                    32: "\Sigma "
                    33: "\Upsilon "
                    34: "\Phi "
                    35: "\Psi "
                    36: "\Omega "}

class equation:
  """A class to store the output of a CNN determining an equation of variable that can be printed to LaTeX code
  """
  
  def __init__(self, vals, states):
    """Class initializer
    
    Args: 
        vals (int list): list of ints that appear represent sequentially appearing characters in the equation
        states (int list): list of states corresponding to each character that denote superscript, subscript, or normal character
    """
    assert len(vals) == len(states),'vals and states should be the same size'
    self.terms = vals
    self.states = states
  
  def appendTerm(self, val, state):
    """Append another term onto the end of an existing equation
    
    Args:
        val (int): Value representing character to append on
        state (int): State of value, 1 = superscript, 0 = normal, -1 = subscript
    """
    self.terms.append(val)
    self.states.append(state)
    
  def printLatex(self):
    """Output a string of LaTeX code that would generate the eqution represented by this object
    """
    
    global specialCharacters
    
    latex = "$"
    prevState = 0
    for term,state in zip(self.terms, self.states):
      # Handle sub/superscript with state
      if prevState != state:
        # Only change states if current state is different than previous
        if prevState == 0:
          if state == 1:
            # Start a superscript from normal
            latex = latex + "^{"
          elif state == -1:
            # Start a supscript from normal
            latex = latex + "_{"
        else:  # previous state was not normal
          if state == 0:
            # End previous special state and enter normal state
            latex = latex + "}"
          elif state == 1:
            # End previous special state and enter superscirpt state
            latex = latex + "}^{"
          elif state == -1:
            # End previous special state and enter supscirpt state
            latex = latex + "}_{"
          
      # Print out term
      if term in specialCharacters:
        # If a special character add the corresponding LaTeX shortcut
        latex = latex + specialCharacters[term]
      else:
        # If a normal character add the string
        latex = latex + chr(term)
      prevState = state
    return latex + "$"